version: '3.8'

x-config-settings: &config-settings
  RUN_FLINK_PRODUCER:       "true"
  WORKLOAD:                "0"
  N_NODES:                  "10"
  PARTITIONS_PER_NODE:      "2"
  PRODUCER_SLEEP_MS:        "100"
  PRODUCER_BATCH_SIZE:      "1024" # "128"
  PRODUCER_COUNT:           "20"
  EVENTS_PER_SECOND:        "10000"
  WINDOW_LENGTH:            "10000"
  GARBAGE_COLLECTION_OFFSET: "10"
  FLUSH_THRESHOLD:          "500"
  ENABLE_RATE_LIMIT:        "false"
  PROCESSING_RATE_LIMIT:    "10000"
  TOPIC_METRICS_INTERVAL:   "5000"
  USE_LOG_FILE:             "true"
  RUN_MAX_THROUGHPUT_PRODUCER: "false"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  RUNTIME: "800000"
  SLEEP_BETWEEN_POLLS: "0"
  GOOGLE_APPLICATION_CREDENTIALS: /app/.gcp/gcs-service-account.json
  GOOGLE_FIRESTORE_CREDENTIALS: /app/.gcp/firebase-user-account.json


x-taskmanager-defaults: &taskmanager-defaults
  image: flink:1.18
  depends_on:
    - jobmanager
  command: taskmanager
  volumes:
    - /home/jonas_spenger/projects/holon/flink-experiments/flink-connectors:/opt/flink/lib/user
    - /home/jonas_spenger/projects/holon/flink-experiments/flink-checkpoints:/flink-checkpoints
    - /home/jonas_spenger/projects/holon/flink-experiments/flink-logs:/opt/flink/log
  environment:
    FLINK_PROPERTIES: |
      jobmanager.rpc.address: jobmanager
      taskmanager.numberOfTaskSlots: 2
      state.checkpoints.dir:    file:///flink-checkpoints/checkpoints
      state.savepoints.dir:     file:///flink-checkpoints/savepoints
      state.backend:            filesystem
      execution.checkpointing.interval:      5000
      execution.checkpointing.tolerable-failed-checkpoints: 5
      execution.checkpointing.max-concurrent-checkpoints:   1
      heartbeat.interval:       10000
      heartbeat.timeout:        30000

services:

#  FLINK SERVICES

  jobmanager:
    image: flink:1.18
    container_name: flink-jobmanager
    user: root
    ports:
      - "8081:8081"
      - "6123:6123"
    command: jobmanager
    volumes:
      - /home/jonas_spenger/projects/holon/flink-experiments/flink-connectors:/opt/flink/lib/user
      - /home/jonas_spenger/projects/holon/flink-experiments/queries:/opt/flink/queries
      - /home/jonas_spenger/projects/holon/flink-experiments/flink-checkpoints:/flink-checkpoints
      - /home/jonas_spenger/projects/holon/flink-experiments/flink-logs:/opt/flink/log
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.checkpoints.dir: file:///flink-checkpoints/checkpoints
        state.savepoints.dir:  file:///flink-checkpoints/savepoints
        state.backend:         filesystem
        execution.checkpointing.interval:      5000
        execution.checkpointing.tolerable-failed-checkpoints: 5
        execution.checkpointing.max-concurrent-checkpoints:   1
        heartbeat.interval:       10000
        heartbeat.timeout:        30000

  taskmanager:
    <<: *taskmanager-defaults

  #  KAFKA SERVICES
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "29092:9092"

#  init-kafka:
#    build:
#      context: ./docker/init-kafka
#      dockerfile: Dockerfile
#    depends_on:
#      - kafka
#    environment:
#      - N_NODES=10

  init-kafka:
    image: rubyies/flink-init-kafka-full-deployment:latest
    depends_on:
      - kafka
    environment:
      <<: *config-settings
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "sh /init-kafka.sh"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

#  HOLON SERVICES
  nexmark-producers:
    image: rubyies/flink-nexmark-producers-full-deployment:latest
    depends_on:
      - init-kafka
    environment:
      <<: *config-settings
      PRODUCER_COUNT: "20"
    volumes:
      - /home/jonas_spenger/projects/holon/flink-experiments/flink-logs:/app/logs

  output-consumer:
    image: rubyies/flink-json-output-consumer-full-deployment:latest
    container_name: output-consumer
    depends_on:
      - init-kafka
      - kafka
    environment:
      <<: *config-settings
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    volumes:
      - /home/jonas_spenger/projects/holon/flink-experiments/flink-logs:/app/logs

  log-consumer:
    image: rubyies/flink-log-append-output-consumer-full-deployment:latest
    container_name: log-consumer
    depends_on:
      - init-kafka
      - kafka
    environment:
      <<: *config-settings
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    volumes:
      - /home/jonas_spenger/projects/holon/flink-experiments/flink-logs:/app/logs

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.50.0.0/16