{{- range $i := until (.Values.holon.n_nodes | int) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: holon-node-{{ $i }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: holon-node-{{ $i }}
spec:
  replicas: {{ $.Values.holon.replicas | int }}
  selector:
    matchLabels:
      app: holon-node-{{ $i }}
  template:
    metadata:
      labels:
        app: holon-node-{{ $i }}
    spec:
      containers:
        - name: holon-node-{{ $i }}
          image: {{ $.Values.holon.image }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: NODE_ID
              value: "{{ $i }}"
            - name: N_NODES
              value: "{{ $.Values.holon.n_nodes }}"
            - name: PARTITIONS_PER_NODE
              value: "{{ $.Values.holon.partitions_per_node }}"
            - name: SLEEP_BETWEEN_POLLS
              value: "{{ $.Values.holon.sleep_between_polls }}"
            - name: RUNTIME
              value: "{{ $.Values.holon.runtime }}"
          volumeMounts:
            - name: holon-storage
              mountPath: /app/snapshots
          {{- if $.Values.holon.resources }}
          resources:
            requests:
              cpu: {{ $.Values.holon.resources.requests.cpu | quote }}
              memory: {{ $.Values.holon.resources.requests.memory | quote }}
            limits:
              cpu: {{ $.Values.holon.resources.limits.cpu | quote }}
              memory: {{ $.Values.holon.resources.limits.memory | quote }}
          {{- end }}
      volumes:
        - name: holon-storage
          persistentVolumeClaim:
            claimName: holon-node-{{ $i }}-pvc
{{- end }}
