apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexmark-producer-0
spec:
  replicas: {{ .Values.nexmarkProducer.replicas }}
  selector:
    matchLabels:
      io.kompose.service: nexmark-producer-0
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --stdout
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: nexmark-producer-0
    spec:
      containers:
        - name: nexmark-producer-0
          image: {{ .Values.nexmarkProducer.image }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: N_NODES
              value: "{{ .Values.holon.n_nodes }}"
            - name: PARTITIONS_PER_NODE
              value: "{{ .Values.holon.partitions_per_node }}"
            - name: PRODUCER_SLEEP_TIME_MS
              value: "{{ .Values.nexmarkProducer.sleepTimeMs }}"
{{/*          resources:*/}}
{{/*            requests:*/}}
{{/*              cpu: "250m"*/}}
{{/*              memory: "512Mi"*/}}
{{/*            limits:*/}}
{{/*              cpu: "500m"*/}}
{{/*              memory: "1Gi"*/}}
      restartPolicy: Always