version = "3.7.15"
runner.dialect = scala3

maxColumn = 160

rewrite.trailingCommas.style = "keep"

docstrings.wrapMaxColumn = 80

rewrite.rules = [Imports]
rewrite.imports.sort = original
rewrite.imports.expand = true
rewrite.imports.groups = [
  ["java.*"],
  ["scala.*"],
  ["pekko.*"],
  ["upickle.*"],
  ["org.*"],
  ["com.*"],
  ["ch.*"],
  ["holon.*"],
]
