pekko {
  actor {
    provider = "cluster"
    allow-java-serialization = on
  }

  remote {
    artery {
      canonical {
        hostname = "127.0.0.1"
        port = 25520
      }
    }
  }

  cluster {
    seed-nodes = [
      "pekko://MyActorSystem@127.0.0.1:25520"
    ]
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }

  # Default Pekko configurations for logging
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"
}