holon:
  image: gcr.io/<project_name>/holon-node:latest
  n_nodes: 5
  partitions_per_node: 2
  runtime: 120000
  runtime_n0: 120000
  runtime_n3: 120000
  recovery_sleeptime: 10000
  sleep_between_polls: 0
  replicas: 1
  window_length: 10000
  checkpoint_interval: 5000
  failure_detection_threshold: 500
  heartbeat_interval: 100

nexmarkProducer:
  image: gcr.io/<project_name>/nexmark-producer:latest
  replicas: 1
  n_producers: 1
  sleepTimeMs: 75

outputConsumer:
  image: gcr.io/<project_name>/output-consumer:latest
  replicas: 1