holon:
  n_nodes: 5
  partitions_per_node: 3
  runtime: 12000000
  runtime_n0: 120000
  runtime_n3: 120000
  recovery_sleeptime: 10000
  sleep_between_polls: 0
  replicas: 1
  window_length: 10000
  checkpoint_interval: 5000
  failure_detection_threshold: 500
  heartbeat_interval: 100

nexmarkProducer:
  image: gcr.io/holon-458408/nexmark-producer-json:latest
  replicas: 1
  n_producers: 1
  sleepTimeMs: 100

outputConsumer:
  image: gcr.io/holon-458408/output-consumer-json:latest
  replicas: 1

lagAppendOutputConsumer:
  image: gcr.io/holon-458408/lag-append-output-consumer-threaded:latest