apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --stdout
    kompose.version: 1.35.0 (HEAD)
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --stdout
        kompose.version: 1.35.0 (HEAD)
      labels:
        app: kafka
    spec:
{{/*      nodeSelector:*/}}
{{/*        node-type: basic*/}}
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: kraft-cluster-id
            - name: KAFKA_CFG_PROCESS_ROLES
              value: controller,broker
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 0@localhost:9093
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          ports:
            - containerPort: 9092
              protocol: TCP

      restartPolicy: Always