holon:
  image: gcr.io/holon-450608/holon-node:latest
  n_nodes: 3
  partitions_per_node: 2
  runtime: 300000
  sleep_between_polls: 0
  storage: 100Mi

nexmarkProducer:
  image: gcr.io/holon-450608/nexmark-producer:latest
  replicas: 1
  sleepTimeMs: 500

outputConsumer:
  image: gcr.io/holon-450608/output-consumer:latest