apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: init-kafka
  name: init-kafka-cm0
data:
  init-kafka.sh: |-
    #!/bin/sh

    # wait until Kafka is reachable
    until kafka-topics --bootstrap-server kafka:9092 --list > /dev/null 2>&1; do
      echo "Waiting for Kafka to be available..."
      sleep 1
    done

    echo "N_NODES: $N_NODES"
    echo "PARTITIONS_PER_NODE: $PARTITIONS_PER_NODE"
    TOTAL_PARTITIONS=$((N_NODES * PARTITIONS_PER_NODE))
    echo "TOTAL_PARTITIONS: $TOTAL_PARTITIONS"

    kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic input --replication-factor 1 --partitions $TOTAL_PARTITIONS  --config message.timestamp.type=LogAppendTime
    kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic output --replication-factor 1 --partitions $TOTAL_PARTITIONS  --config message.timestamp.type=LogAppendTime

    echo "Successfully created topics:"
    kafka-topics --bootstrap-server kafka:9092 --list
