version: '3.8'

services:
  jobmanager:
    image: flink:1.18
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./flink-connectors:/opt/flink/lib/user
      - ./queries:/opt/flink/queries
      - ./flink-checkpoints:/flink-checkpoints
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.checkpoints.dir: file:///flink-checkpoints/checkpoints
        state.savepoints.dir: file:///flink-checkpoints/savepoints
        state.backend: filesystem
        execution.checkpointing.interval: 5000
        execution.checkpointing.tolerable-failed-checkpoints: 5
        execution.checkpointing.max-concurrent-checkpoints: 1
        heartbeat.interval: 10000
        heartbeat.timeout: 30000

  taskmanager1:
    image: flink:1.18
    container_name: flink-taskmanager1
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./flink-connectors:/opt/flink/lib/user
      - ./flink-checkpoints:/flink-checkpoints
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1
        state.checkpoints.dir: file:///flink-checkpoints/checkpoints
        state.savepoints.dir: file:///flink-checkpoints/savepoints
        state.backend: filesystem
        execution.checkpointing.interval: 5000
        execution.checkpointing.tolerable-failed-checkpoints: 5
        execution.checkpointing.max-concurrent-checkpoints: 1
        heartbeat.interval: 10000
        heartbeat.timeout: 30000

  taskmanager2:
    image: flink:1.18
    container_name: flink-taskmanager2
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./flink-connectors:/opt/flink/lib/user
      - ./flink-checkpoints:/flink-checkpoints
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1
        state.checkpoints.dir: file:///flink-checkpoints/checkpoints
        state.savepoints.dir: file:///flink-checkpoints/savepoints
        state.backend: filesystem
        execution.checkpointing.interval: 5000
        execution.checkpointing.tolerable-failed-checkpoints: 5
        execution.checkpointing.max-concurrent-checkpoints: 1
        heartbeat.interval: 10000
        heartbeat.timeout: 30000

#  taskmanager3:
#    image: flink:1.18
#    container_name: flink-taskmanager3
#    depends_on:
#      - jobmanager
#    command: taskmanager
#    volumes:
#      - ./flink-connectors:/opt/flink/lib/user
#    environment:
#      - |
#        FLINK_PROPERTIES=
#        jobmanager.rpc.address: jobmanager
#        taskmanager.numberOfTaskSlots: 1
#
#  taskmanager4:
#    image: flink:1.18
#    container_name: flink-taskmanager4
#    depends_on:
#      - jobmanager
#    command: taskmanager
#    volumes:
#      - ./flink-connectors:/opt/flink/lib/user
#    environment:
#      - |
#        FLINK_PROPERTIES=
#        jobmanager.rpc.address: jobmanager
#        taskmanager.numberOfTaskSlots: 1
#
#  taskmanager5:
#    image: flink:1.18
#    container_name: flink-taskmanager5
#    depends_on:
#      - jobmanager
#    command: taskmanager
#    volumes:
#      - ./flink-connectors:/opt/flink/lib/user
#    environment:
#      - |
#        FLINK_PROPERTIES=
#        jobmanager.rpc.address: jobmanager
#        taskmanager.numberOfTaskSlots: 1

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka
    volumes:
      - ./init-kafka.sh:/init-kafka.sh
    environment:
      N_NODES: "2"
    entrypoint: [ "/bin/sh", "-c", "sh /init-kafka.sh" ]


  # Optional: Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  nexmark-producer-json:
    build:
      context: ../..
      dockerfile: ../flink/docker/nexmark-producer-json/Dockerfile
    depends_on:
      - init-kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      PRODUCER_SLEEP_TIME_MS: "500"
      N_NODES: "2"
      PARTITIONS_PER_NODE: "1"

  output-consumer:
    build:
      context: ../..
      dockerfile: ../flink/docker/output-consumer-json/Dockerfile
    depends_on:
      - init-kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
